apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-stage
resources:
  - ../../base/podinfo
patches:
  - path: podinfo-patch.yaml
    target:
      kind: HelmRelease
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-stage
resources:
  - ../../base/apps/helm.yaml
patchesStrategicMerge:
  - helm-patch.yaml
