apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-stage
resources:
  - ../../base/podinfo
patchesStrategicMerge:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease